name: mitul_s_application4
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  dotted_border: 2.0.0+3
  flutter_rating_bar: ^4.0.0
  carousel_slider: ^4.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsLightItalic.ttf
          weight: 300
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/OpenSansRomanBold.ttf
          weight: 700
    - family: Tinos
      fonts: 
        - asset: assets/fonts/TinosBold.ttf
          weight: 700
